# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = """
$username\
$hostname \
$shell\
$directory\
$git_branch\
$git_status\
$git_commit\
$nodejs\
$python
$character"""

# The name of the module we are configuring
[character]
success_symbol = '[\$](bold white)'
error_symbol = '[󱎘](bold red)'

[directory]
style = "bold yellow"
truncation_length = 4
truncation_symbol = '…/'

[git_branch]
symbol = '󰘬 '

[hostname]
ssh_only = false
style = 'bold green'
format = '[@$hostname]($style)'

[shell]
style = "bold purple"
powershell_indicator = "PWSH"
disabled = false

[username]
show_always = true
style_user = 'bold green'
format = '[$user]($style)'
