# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = """
$directory\
$git_branch\
$git_status\
$git_commit\
$nodejs\
$python
$character"""

# The name of the module we are configuring
[character]
success_symbol = '[󰁕](bold green)'
error_symbol = '[󱎘](bold red)'

[directory]
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = "󰘬 "
